export default {
  PRIMARY_BACKGROUND_COLOR: '#F5F5F5',
  WHITE: '#FFFFFF',
  SHOPPING_BAG_NUMBER_COLOR: '#00B495',
  BACKGROUND_SEARCH_INPUT_COLOR: '#EAEAEA',
  PLACEHOLDER_SEARCH_INPUT_TEXT_COLOR: '#555555'
}
